				<section class="page-header">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul class="breadcrumb">
									<li><a href="#">Administrace</a></li>
									<li class="active">Nastavení webu</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1>Nastavení webu</h1>
    							</div>
						</div>
					</div>
				</section>
				<div class="container">
					<div class="row">
    <form action="" method="post">
<table class="table table-bordered">
    <tr><td>Klíčová slova :</td><td><input type="text" name="keywords" class="form-control input-group-lg" value="<?= $keywords ?>" ></td></tr>
    <tr><td>Popis webu :</td><td><input type="text" name="description" class="form-control input-group-lg" value="<?= $description ?>" ></td></tr>
    <tr><td>Titulek webu :</td><td><input type="text" name="title" class="form-control input-group-lg" value="<?= $title ?>" ></td></tr>
    <tr><td>Footer :</td><td><textarea class="form-control input-group-lg" name="footer" rows="15"> <?= $footer ?></textarea></td></tr>
    <tr><td colspan="2" align="right"><input style="text-align: right;" type="submit" name="Ulozit" value="Uložit"></td></tr>
</table>
    </form>
                                        </div>
                                </div>