				<section class="page-header">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul class="breadcrumb">
									<li><a href="#">Administrace</a></li>
									<li class="active">Články</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1>Administrace článků</h1>
    							</div>
						</div>
					</div>
				</section>
				<div class="container">
					<div class="row">
<table class="table table-hover">
          <tr>
       <th>Název</th>   
       <th>Pořadí</th>   
       <th>Náhled</th>   
       <th>Smazat</th>   
       </tr>
<?php 

    $index=0;
    $last = count($clanky)-1;
    foreach ($clanky as $clanek) :  
        if (!$index) $sipkanahoru='';
        else $sipkanahoru='<a href="adminClanek/posunnahoru/'.$clanek['clanky_id'].'/'.$clanek['poradi'].'">▲</a>';
        if ($index==$last) $sipkadolu='';
        else $sipkadolu='<a href="adminClanek/posundolu/'.$clanek['clanky_id'].'/'.$clanek['poradi'].'">▼</a>';
    ?>       
       <tr>
            <td><a href="clanek/<?= $clanek['url'] ?>"><?= $clanek['titulek'] ?></td>
            <td><?= $sipkanahoru.'</br>'.$sipkadolu ?></td>
            <td><a href="adminclanek/<?= $clanek['url'] ?>">Upravit</td>
            <td><a href="adminclanek/vymaz/<?= $clanek['clanky_id'] ?>" title="Vymazat">X</a></td>
       </tr>
<?php     
    $index++;
    endforeach
    
?>
   </table>
        <p>
        <h3><a href="adminclanek/novy">Přidat nový článek</h3>
        </p>


                                        </div>
                                </div>

 
    