				<section class="page-header">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<h1><?= $titulek ?></h1>
							</div>
						</div>
					</div>
				</section>
				<div class="container">
					<div class="row">
                                            <?= $_obsah; ?>
                                        </div>
                                </div>
