                        <?php 
                        
                                
                                
                        if (!$_homepage) { ?>            
                                <div class="container">
					<div class="row">
                                            <?php
                                            }
                                            ?>
                                            
                                            <?= $_obsah; ?>
                        <?php if (!$_homepage) { ?>            
                                        </div>
                                </div>
                                            <?php
                                            }
                                            ?>
