				<section class="page-header">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<h1>Kontakt</h1>
    							</div>
						</div>
					</div>
				</section>
                                <div class="container">
                                    <div class="row">
						<div class="col-md-6">
                                                    <h2 class="mb-sm mt-sm">Kontaktní údaje</h2>
							<ul class="list list-icons list-icons-style-1 mt-xlg">
								<li><i class="fa fa-phone"></i> <strong>Telefon:</strong> +420 605 260 772</li>
								<li><i class="fa fa-envelope"></i> <strong>Email:</strong> <a href="mailto:info@ctiborvenus.eu">info@ctiborvenus.eu</a></li>
								<li><i class="fa fa-skype"></i> <strong>Skype:</strong> <a href="<a href="skype:martyql?call">martyql</a></li>
                                                                <li><i class="fa fa-info"></i> <strong>IČO:</strong> 03773540</p></li>
                                                                <li><i class="fa fa-bank"></i> <strong>Bankovní spojení:</strong> 2630709013/0800</p></li>
								<li><i class="fa fa-map-marker"></i> <strong>Address:</strong> Řídeč 330, Šternberk 78501</li>
							</ul>
							<hr>                                                    

	
                                                        
                                                    
                                                </div>
						<div class="col-md-6">
                                                        <?php if ($odeslano) {?>
							<h4 class="heading-primary mt-lg">Zpráva byla odeslána!</h4>
							<p><?=$textodeslano?></p>
                                                        <?php }
                                                        else  {
                                                        ?>
                                                        <?php if ($chyba) {?>
							<div class="alert alert-danger " id="contactError">
								<?= $chyba ?>
							</div>
                                                        <?php } ?>
							<h2 class="mb-sm mt-sm">Kontaktní <strong>formulář</strong></h2>
							<form id="contactForma"  method="POST" >
								<input type="hidden" value="true" name="emailSent" id="emailSent">
								<div class="row">
									<div class="form-group">
										<div class="col-md-6">
											<label>Vaše jméno *</label>
											<input type="text" value="<?=$jmeno?>" data-msg-required="Prosím uveďte Vaše jméno." maxlength="100" class="form-control" name="name" id="name" required>
										</div>
										<div class="col-md-6">
											<label>Váš email *</label>
											<input type="email" value="<?=$email?>" data-msg-required="Prosím uveďte Váš email." data-msg-email="Prosím uveďte validní emailovou adresu." maxlength="100" class="form-control" name="email" id="email" required>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="form-group">
                                                                                <div class="col-md-6">
                                                                                <label>Typ požadované služby *</label>
                                                                                <select data-msg-required="Prosím vyberte položku ze seznamu." class="form-control" name="sluzba" id="subject" required>
                                                                                        <option value="">...</option>
                                                                                       <?php foreach ($moznosti as $moznost) {?>

                                                                                        <option value="<?= $moznost['id'] ?>" <?php if ($typsluzby==$moznost['id']) echo "selected";  ?>><?= $moznost['nazev'] ?></option>
                                                                                        <?php }?>
                                                                                </select>
                                                                                </div>
                                                                                <div class="col-md-6">
                                                                                        <label>Váš telefon</label>
                                                                                        <input type="phone" value="<?=$telefon?>"  maxlength="100" class="form-control" name="phone" id="phone">
                                                                                </div>

                                                                        </div>
								</div>
								<div class="row">
									<div class="form-group">
										<div class="col-md-12">
											<label>Zpráva *</label>
											<textarea maxlength="6000" data-msg-required="Prosím napište Vaši zprávu." rows="8" class="form-control" name="message" id="message" required><?= $zprava?></textarea>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="form-group">
                                                                        <div class="col-md-12">
                                                                                <label>Příloha</label>
                                                                                <input type="file" name="attachment" id="attachment">
                                                                        </div>
									</div>
								</div>
								<div class="row">
									<div class="form-group">
									<div class="col-md-12">
										<label>Ochrana proti botům * (dvě plus čtyři je - vyplňte číslo)</label>
                                                                                <input type="text" value="" data-msg-required="dvě plus čtyři je - vyplňte číslo." maxlength="50" class="form-control" name="antispam" id="antispam" required>
									</div>
                                                                        </div>
                                                                </div>
								<div class="row">
									<div class="col-md-12">
										<hr>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<input type="submit" name="odeslat" value="Odeslat zprávu" class="btn btn-primary btn-lg pull-right" >
									</div>
								</div>
							</form>
                                                        <?php } ?>
                                                        
						</div>

					</div>
                                </div>
	
        
                                </div>

