<!DOCTYPE html>
<html>
	<head>

		<!-- Basic -->
		<base href="/" />
		<meta charset="utf-8">
                <meta http-equiv="X-UA-Compatible" content="IE=edge">	

		<title><?= $titulek ?></title>

		<meta name="keywords" content="PHP, MySQL, tvorba webových stránek, www stránky, webové stránky,internetový obchod, e-shop, redakční systém, servis, servis PC, LAN, Linux, Windows, Joomla, Visual Basic, správa webu,design, webdesign, šternberk, uničov, paseka" />
		<meta name="description" content="Ctibor Venus - it technik a programátor. Zajišťuji servis výpočetní techniky, počítačových sítí, tvorbu a úprava webových stránek na míru včetně hostingu, tvorba softwaru v PHP, .NET.">
                <meta name="author" content="Ctibor Venus">
                <meta name="robots" content="index, follow" /> 

		<!-- Favicon -->
		<link rel="shortcut icon" href="/assets/img/favicon.ico" type="image/x-icon" />
		<link rel="apple-touch-icon" href="/assets/img/apple-touch-icon.png">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.css">
		<link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.css">
		<link rel="stylesheet" href="/assets/vendor/simple-line-icons/css/simple-line-icons.css">
		<link rel="stylesheet" href="/assets/vendor/owl.carousel//assets/owl.carousel.min.css">
		<link rel="stylesheet" href="/assets/vendor/owl.carousel//assets/owl.theme.default.min.css">
		<link rel="stylesheet" href="/assets/vendor/magnific-popup/magnific-popup.css">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="/assets/css/theme.css">
		<link rel="stylesheet" href="/assets/css/theme-elements.css">
		<link rel="stylesheet" href="/assets/css/theme-blog.css">
		<link rel="stylesheet" href="/assets/css/theme-shop.css">
		<link rel="stylesheet" href="/assets/css/theme-animate.css">

		<!-- Current Page CSS -->
		<link rel="stylesheet" href="/assets/vendor/rs-plugin/css/settings.css" media="screen">
		<link rel="stylesheet" href="/assets/vendor/rs-plugin/css/layers.css" media="screen">
		<link rel="stylesheet" href="/assets/vendor/rs-plugin/css/navigation.css" media="screen">
		<link rel="stylesheet" href="/assets/vendor/circle-flip-slideshow/css/component.css" media="screen">

		<!-- Skin CSS -->
		<link rel="stylesheet" href="/assets/css/skins/default.css">

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="/assets/css/custom.css">

		<!-- Head Libs -->
		<script src="/assets/vendor/modernizr/modernizr.js"></script>
                <?php if ($_SESSION['admin']==1) { ?>
                        <script type="text/javascript" src="assets/js/tinymce/tinymce.min.js"></script>
                        <script type="text/javascript" src="assets/js/tinymce/tinymcestart.js"> </script>
                <?php } ?>

	</head>
	<body>
		<div class="body">
			<header id="header" data-plugin-options='{"stickyEnabled": true, "stickyEnableOnBoxed": true, "stickyEnableOnMobile": true, "stickyStartAt": 57, "stickySetTop": "-57px", "stickyChangeLogo": true}'>
				<div class="header-body">
					<div class="header-container container">
						<div class="header-row">
							<div class="header-column">
								<div class="header-logo">
									<a href="/">
                                                                            <img alt="Ctibor Venus" height="60" data-sticky-height="40" data-sticky-top="33" src="/assets/img/cv.jpg">
									</a>
								</div>
                                                                
                                                           

  						</div>
							<div class="header-column">
								<div class="header-row">
									<div class="header-search hidden-xs">
										<form id="searchForm" action="/hledat" method="get">
											<div class="input-group">
												<input type="text" class="form-control" name="q" id="q" placeholder="Hledat..." required>
												<span class="input-group-btn">
													<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
												</span>
											</div>
										</form>
									</div>
									<nav class="header-nav-top">
										<ul class="nav nav-pills">
											<li class="hidden-xs">
												
											</li>
											<li class="hidden-xs">
												<a href="/kontakt"><i class="fa fa-angle-right"></i> Kontaktujte mě</a>
											</li>
											<li>
												<span class="ws-nowrap"><i class="fa fa-envelope"></i> info@ctiborvenus.eu</span>
											</li>
										</ul>
									</nav>
								</div>
								<div class="header-row">
									<div class="header-nav">
										<button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main">
											<i class="fa fa-bars"></i>
										</button>
										<ul class="header-social-icons social-icons hidden-xs">
											<li class="social-icons-facebook"><a href="http://www.facebook.com/ctiborvenus" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
											<li class="social-icons-twitter"><a href="http://twitter.com/CtiborV" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
											<li class="social-icons-linkedin"><a href="https://cz.linkedin.com/pub/ctibor-venus/b7/523/331" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
										</ul>
										<div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1 collapse">
                                                                                    <nav>
                                                                                        <ul class="nav nav-pills" id="mainNav">
                                                                                    
                                                                                                                      <?php foreach ($menus as $menu) {?>
                                                                                            <li <?php if ($menu['aktivni']) echo "class=\"active\"";  ?>>
                                                                                                <a href="<?= $menu['url'] ?>"  ><?= $menu["nazev"] ?></a>
                                                                                            </li>
                                                                    <?php }?>
                                                                                        </ul>
                                                                                    </nav>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</header>

			<div role="main" class="main">
			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
                        </div>
			<div id="footer-wrapper">
			<footer id="footer">
				<div class="container">
					<div class="row">
						<div class="footer-ribbon">
							<span>Zkontaktovat</span>
						</div>             
						<div class="col-md-3">
							<div class="contact-details">
								<h4>Kontakt</h4>
								<ul class="contact">
									<li><p><i class="fa fa-map-marker"></i> <strong>Addresa:</strong> Řídeč 330, Šternberk, 78501</p></li>
									<li><p><i class="fa fa-phone"></i> <strong>Telefon:</strong> + 420 605 260 772</p></li>
									<li><p><i class="fa fa-envelope"></i> <strong>Email:</strong> <a href="mailto:info@ctiborvenus.eu">info@ctiborvenus.eu</a></p></li>
								</ul>
							</div>
						</div>
						<div class="col-md-3">
							<h4>Fakturační údaje</h4>
								<ul class="contact">
									<li><p><i class="fa fa-list"></i> <strong>IČO:</strong> 03773540</p></li>
									<li><p><i class="fa fa-bank"></i> <strong>Bankovní spojení:</strong> 2630709013/0800</p></li>
								</ul>
						</div>
						<div class="col-md-3">
							<h4>Socilální sítě</h4>
							<ul class="social-icons">
								<li class="social-icons-facebook"><a href="http://www.facebook.com/ctiborvenus" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
								<li class="social-icons-twitter"><a href="http://twitter.com/CtiborV" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
								<li class="social-icons-linkedin"><a href="https://cz.linkedin.com/pub/ctibor-venus/b7/523/331" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
							</ul>
						</div>
						<div class="col-md-3">
							<h4>O mně</h4>
              <p>Jsem IT specialista, provádím servis výpočetní techniky, tvorbu webových stránek s responsivním designem, úpravy redakčních systému a programování na zakázku.</p>
						</div>
					</div>
				</div>
				<div class="footer-copyright">
					<div class="container">
						<div class="row">
							<div class="col-md-1">
								<a href="index.html" class="logo">
									<img alt="Ctibor Venus.eu" class="img-responsive" src="/assets/img/logo-CVsm.png">
								</a>
							</div>
							<div class="col-md-7">
								<p>© Copyright Ctibor Venus 2015. Všechna práva vyhrazena.</p>
							</div>
							<div class="col-md-4">
								<nav id="sub-menu">
									<ul>
										<li><a href="kontakt">Kontakt</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</footer>
		</div>

		<!-- Vendor -->
		<script src="/assets/vendor/jquery/jquery.js"></script>
		<script src="/assets/vendor/jquery.appear/jquery.appear.js"></script>
		<script src="/assets/vendor/jquery.easing/jquery.easing.js"></script>
		<script src="/assets/vendor/jquery-cookie/jquery-cookie.js"></script>
		<script src="/assets/vendor/bootstrap/js/bootstrap.js"></script>
		<script src="/assets/vendor/common/common.js"></script>
		<script src="/assets/vendor/jquery.validation/jquery.validation.js"></script>
		<script src="/assets/vendor/jquery.stellar/jquery.stellar.js"></script>
		<script src="/assets/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js"></script>
		<script src="/assets/vendor/jquery.gmap/jquery.gmap.js"></script>
		<script src="/assets/vendor/jquery.lazyload/jquery.lazyload.js"></script>
		<script src="/assets/vendor/isotope/jquery.isotope.js"></script>
		<script src="/assets/vendor/owl.carousel/owl.carousel.js"></script>
		<script src="/assets/vendor/magnific-popup/jquery.magnific-popup.js"></script>
		<script src="/assets/vendor/vide/vide.js"></script>

		
		<!-- Theme Base, Components and Settings -->
		<script src="/assets/js/theme.js"></script>
		
		<!-- Current Page Vendor and Views -->
		<script src="/assets/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
		<script src="/assets/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
		<script src="/assets/vendor/circle-flip-slideshow/js/jquery.flipshow.js"></script>

                <?php if ($js)  echo '<script src="/assets/js/views/'.$js.'"></script>';  ?> 
                
		<!-- Current Page Vendor and Views -->
		<script src="assets/js/views/view.contact.js"></script>		
		<!-- Theme Custom -->
		<script src="/assets/js/custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="/assets/js/theme.init.js"></script>


                

		<!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information.
		<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64905220-1', 'auto');
  ga('send', 'pageview');
  	</script>
		 -->

	</body>
</html>